eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

api:
  prefix: api
  version: v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
      discovery:
        locator:
          enabled: true
      routes:
        - id: conversation-service
          uri: lb://conversation-service
          predicates:
            - Path=/${api.prefix}/${api.version}/conversations/**, 
              /${api.prefix}/${api.version}/conversation-members/**, 
              /v3/api-docs/conversation-service

        - id: friend-service
          uri: lb://friend-service
          predicates:
            - Path=/${api.prefix}/${api.version}/friends/**, 
              /${api.prefix}/${api.version}/friendships/**, 
              /v3/api-docs/friend-service

        - id: group-service
          uri: lb://group-service
          predicates:
            - Path=/${api.prefix}/${api.version}/groups/**, 
              /${api.prefix}/${api.version}/group-members/**, /${api.prefix}/${api.version}/events/**, 
              /v3/api-docs/group-service

        - id: media-service
          uri: lb://media-service
          predicates:
            - Path=/${api.prefix}/${api.version}/albums/**, 
              /${api.prefix}/${api.version}/files/**, 
              /v3/api-docs/media-service

        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/${api.prefix}/${api.version}/messages/**, 
              /v3/api-docs/message-service

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/${api.prefix}/${api.version}/notifications/**, 
              /v3/api-docs/notification-service

        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/${api.prefix}/${api.version}/posts/**, 
              /${api.prefix}/${api.version}/comments/**, 
              /${api.prefix}/${api.version}/reactions/**, 
              /v3/api-docs/post-service

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/${api.prefix}/${api.version}/users/**, 
              /${api.prefix}/${api.version}/credentials/**, 
              /${api.prefix}/${api.version}/token/**, 
              /${api.prefix}/${api.version}/auth/**,
              /v3/api-docs/user-service
          
        - id: proxy-client
          uri: lb://proxy-client
          predicates:
            - Path=/${api.prefix}/**, 
              /v3/api-docs/proxy-client
              
springdoc:
    swagger-ui:
        urls:
        - name: conversation-service
          url: /v3/api-docs/conversation-service

        - name: friend-service
          url: /v3/api-docs/friend-service

        - name: group-service
          url: /v3/api-docs/group-service

        - name: media-service
          url: /v3/api-docs/media-service

        - name: message-service
          url: /v3/api-docs/message-service

        - name: notification-service
          url: /v3/api-docs/notification-service

        - name: post-service
          url: /v3/api-docs/post-service

        - name: user-service
          url: /v3/api-docs/user-service

        - name: proxy-client
          url: /v3/api-docs/proxy-client
#management:
#  tracing:
#    sampling:
#      probability: 1.0

