eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/

server:
  port: 8800

spring:
  application:
    name: exam-service
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  data:
    mongodb:
      database: exam_service
      uri: mongodb+srv://admin:admin@java-cluster.dydtuf8.mongodb.net/

springdoc:
  packages-to-scan:
    com.trvankiet.app
  api-docs:
    path: /v3/api-docs/exam-service
    
#management:
#  tracing:
#    sampling:
#      probability: 1.0
