eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/

server:
  port: 8300

spring:
  application:
    name: group-service
  data:
    mongodb:
      database: group_service
      uri: mongodb+srv://admin:admin@java-cluster.dydtuf8.mongodb.net/

springdoc:
  packages-to-scan:
    com.trvankiet.app
  api-docs:
    path: /v3/api-docs/group-service
    
#management:
#  tracing:
#    sampling:
#      probability: 1.0
