eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8400

spring:
  application:
    name: media-service
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  data:
    mongodb:
      database: media_service
      uri: mongodb+srv://admin:admin@java-cluster.dydtuf8.mongodb.net/

springdoc:
  packages-to-scan:
    com.trvankiet.app
  api-docs:
    path: /v3/api-docs/media-service

cloudinary:
  cloud-name: djzwxw0ao
  api-key: 137985542995866
  api-secret: mwPz2mtnm-7AaOb4uh8UzqGjiHk

#management:
#  tracing:
#    sampling:
#      probability: 1.0
