eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/

server:
  port: 8700

spring:
  application:
    name: post-service
  data:
    mongodb:
      database: post_service
      uri: mongodb://localhost:27017/

springdoc:
  packages-to-scan:
    com.trvankiet.app
  api-docs:
    path: /v3/api-docs/post-service
    
#management:
#  tracing:
#    sampling:
#      probability: 1.0
